feed_categories:
  ool_specific_resources:
    - title: "Astrobiology (astrobiology.com)"
      url: "https://astrobiology.com/rss"
    - title: "ScienceDaily: Origin of Life News"
      url: "https://www.sciencedaily.com/rss/fossils_ruins/origin_of_life.xml"

  preprints:
    - title: "astro-ph.EP updates on arXiv.org"
      url: "https://arxiv.org/rss/astro-ph.EP"
    - title: "biochemistry - biorXiv Preprints"
      url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=biochemistry"
    - title: "bioinformatics - biorXiv Preprints"
      url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=bioinformatics"
    - title: "biophysics - biorXiv Preprints"
      url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=biophysics"
    - title: "bioRxiv Subject Collection: Evolutionary Biology"
      url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=evolutionary_biology"
    - title: "cell biology - biorXiv Preprints"
      url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=cell_biology"
    - title: "cond-mat.dis-nn updates on arXiv.org"
      url: "http://arxiv.org/rss/cond-mat.dis-nn"
    - title: "cond-mat.stat-mech updates on arXiv.org"
      url: "https://arxiv.org/rss/cond-mat.stat-mech"
    - title: "cs.GT updates on arXiv.org"
      url: "https://arxiv.org/rss/cs.GT"
    - title: "cs.IT updates on arXiv.org"
      url: "https://arxiv.org/rss/cs.IT"
    - title: "cs.NE updates on arXiv.org"
      url: "https://arxiv.org/rss/cs.NE"
    - title: "math-ph updates on arXiv.org"
      url: "https://arxiv.org/rss/math-ph"
    - title: "math.DS updates on arXiv.org"
      url: "https://arxiv.org/rss/math.DS"
    - title: "molecular biology - biorXiv Preprints"
      url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=molecular_biology"
    - title: "nlin.AO updates on arXiv.org"
      url: "http://arxiv.org/rss/nlin.AO"
    - title: "nlin.CD updates on arXiv.org"
      url: "http://arxiv.org/rss/nlin.CD/"
    - title: "nlin.PS updates on arXiv.org"
      url: "http://arxiv.org/rss/nlin.PS"
    - title: "physics.bio-ph updates on arXiv.org"
      url: "http://arxiv.org/rss/physics.bio-ph"
    - title: "physics.chem-ph updates on arXiv.org"
      url: "https://arxiv.org/rss/physics.chem-ph"
    - title: "physics.comp-ph updates on arXiv.org"
      url: "https://arxiv.org/rss/physics.comp-ph"
    - title: "q-bio.BM updates on arXiv.org"
      url: "http://arxiv.org/rss/q-bio.BM"
    - title: "q-bio.MN updates on arXiv.org"
      url: "http://arxiv.org/rss/q-bio.MN"
    - title: "q-bio.PE updates on arXiv.org"
      url: "https://arxiv.org/rss/q-bio.PE"
    - title: "systems biology - biorXiv Preprints"
      url: "https://connect.biorxiv.org/biorxiv_xml.php?subject=systems_biology"

  journals_pubmed:
    - title: "Artif Life"
      url: "https://pubmed.ncbi.nlm.nih.gov/rss/journals/9433814/?limit=100&name=Artif%20Life&utm_campaign=journals"
    - title: "Evol Comput"
      url: "https://pubmed.ncbi.nlm.nih.gov/rss/journals/9513581/?limit=100&name=Evol%20Comput&utm_campaign=journals"
    - title: "Life (Basel)"
      url: "https://pubmed.ncbi.nlm.nih.gov/rss/journals/101580444/?limit=100&name=Life%20%28Basel%29&utm_campaign=journals"
    - title: "Entropy (Basel)"
      url: "https://pubmed.ncbi.nlm.nih.gov/rss/journals/101243874/?limit=100&name=Entropy%20%28Basel%29&utm_campaign=journals"
    - title: "Astrobiology (Mary Ann Liebert)"
      url: "https://pubmed.ncbi.nlm.nih.gov/rss/journals/101088083/?limit=100&name=Astrobiology&utm_campaign=journals"

  journals:
    - title: "ACS Synthetic Biology"
      url: "https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=asbcd6"
    - title: "Annual Reviews: Analytical Chemistry"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=6690&jc=anchem&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Astronomy and Astrophysics"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=6690&jc=astro&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Biochemistry"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=se&jc=biochem&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Biophysics"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=s7&jc=biophys&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Condensed Matter Physics"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=68t8&jc=conmatphys&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Earth and Planetary Sciences"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=s0&jc=earth&type=etoc&feed=atom%20"
      stale_days: 365
    - title: "Annual Reviews: Ecology, Evolution, and Systematics"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=sh&jc=ecolsys&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Genetics"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=sj&jc=genet&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Microbiology"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=sn&jc=micro&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Physical Chemistry"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=sy&jc=physchem&type=etoc&feed=atom"
      stale_days: 365
    - title: "Annual Reviews: Virology"
      url: "https://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=6690&jc=virology&type=etoc&feed=atom"
      stale_days: 365
    - title: "BioEssays"
      url: "http://onlinelibrary.wiley.com/rss/journal/10.1002/(ISSN)1521-1878"
    - title: "Biosystems"
      url: "https://rss.sciencedirect.com/publication/science/03032647"
    - title: "Chaos: An Interdisciplinary Journal of Nonlinear Science"
      url: "https://pubs.aip.org/rss/site_1000025/1000015.xml"
    - title: "PLOS Complex Systems"
      url: "https://journals.plos.org/complexsystems/feed/atom"
    - title: "eLife - recent issues"
      url: "https://elifesciences.org/rss/recent.xml"
    - title: "J Syst Sci Complex"
      url: "https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=11424"
    - title: "Journal of Computational Science"
      url: "https://rss.sciencedirect.com/publication/science/18777503"
    - title: "Journal of Evolutionary Biology (Latest Issue)"
      url: "https://academic.oup.com/rss/site_6606/4185.xml"
      stale_days: 90
    - title: "Journal of Evolutionary Biology (Advance Articles)"
      url: "https://academic.oup.com/rss/site_6606/advanceAccess_4185.xml"
    - title: "Journal of The Royal Society Interface"
      url: "https://royalsocietypublishing.org/rss/site_1000019/1000012.xml"
    - title: "Journal of Theoretical Biology"
      url: "https://rss.sciencedirect.com/publication/science/00225193"
    - title: "Nature Chemistry"
      url: "http://www.nature.com/nchem/current_issue/rss/"
    - title: "Nature Communications"
      url: "http://feeds.nature.com/ncomms/rss/current"
    - title: "Nature Ecology & Evolution Community"
      url: "https://natureecoevocommunity.nature.com/rss.xml"
    - title: "nature.com - Astronomy and astrophysics"
      url: "https://www.nature.com/subjects/astronomy-and-astrophysics.rss"
    - title: "nature.com - Biological sciences"
      url: "https://www.nature.com/subjects/biological-sciences/ncomms.rss"
    - title: "nature.com - Complex networks"
      url: "https://www.nature.com/subjects/complex-networks.atom"
    - title: "nature.com - Nature Physics"
      url: "http://www.nature.com/nphys/current_issue/rss/"
    - title: "npj Complexity"
      url: "https://www.nature.com/npjcomplex/rss"
    - title: "Philosophical Transactions A"
      url: "https://royalsocietypublishing.org/rss/site_1000005/1000005.xml"
    - title: "Philosophical Transactions B"
      url: "https://royalsocietypublishing.org/rss/site_1000007/1000006.xml"
    - title: "Phys. Rev. E"
      url: "http://feeds.aps.org/rss/recent/pre.xml"
    - title: "Phys. Rev. Lett."
      url: "http://feeds.aps.org/rss/recent/prl.xml"
    - title: "Physics of Life Reviews"
      url: "https://rss.sciencedirect.com/publication/science/15710645"
    - title: "PLOS Biology"
      url: "https://journals.plos.org/plosbiology/feed/atom"
    - title: "PLOS Computational Biology"
      url: "http://www.ploscompbiol.org/article/feed"
    - title: "PNAS"
      url: "https://www.pnas.org/rss/ahead.xml"
    - title: "PNAS Evolution"
      url: "http://www.pnas.org/rss/Evolution.xml"
    - title: "Protein Science"
      url: "http://onlinelibrary.wiley.com/rss/journal/10.1002/(ISSN)1469-896X"
    - title: "Science"
      url: "https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=science"
    - title: "Scientific Reports"
      url: "http://feeds.nature.com/srep/rss/current"

  press_releases:
    - title: "Complexity Digest"
      url: "https://comdig.unam.mx/feed/"
    - title: "Phys.org - General Physics News"
      url: "https://phys.org/rss-feed/physics-news/physics/"
    - title: "Phys.org - latest science and technology news stories"
      url: "https://www.physorg.com/rss-feed/"
    - title: "phys.org - Mathematics News"
      url: "https://phys.org/rss-feed/science-news/mathematics/"
    - title: "phys.org - Space News"
      url: "https://phys.org/rss-feed/space-news/"
    - title: "Phys.org: Evolution News"
      url: "http://www.physorg.com/rss-feed/biology-news/evolution/"
    - title: "ScienceDaily - Evolutionary Biology News"
      url: "https://www.sciencedaily.com/rss/plants_animals/evolution.xml"

  magazines:
    - title: "Nature"
      url: "https://www.nature.com/nature.rss"
    - title: "New Scientist - Current Issue Articles"
      url: "http://feeds.newscientist.com/magazine"
    - title: "New Scientist - Life"
      url: "https://feeds.newscientist.com/life"
    - title: "New Scientist - Physics & Math"
      url: "https://feeds.newscientist.com/physics-math"
    - title: "Quanta Magazine"
      url: "https://www.quantamagazine.org/feed/"
    - title: "Scientific American"
      url: "https://www.scientificamerican.com/platform/syndication/rss/"